# Generated by Django 5.2.1 on 2025-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Укажите страну проживания",
                max_length=100,
                null=True,
                verbose_name="Страна проживания",
            ),
        ),
    ]
