# Generated by Django 5.2.1 on 2025-06-24 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=300,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Добавьте содержимое письма",
                        verbose_name="Содержимое письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_sending",
                    models.DateTimeField(
                        help_text="Укажите дату старта рассылки",
                        verbose_name="Дата старта рассылки",
                    ),
                ),
                (
                    "end_sending",
                    models.DateTimeField(
                        help_text="Укажите дату окончания рассылки",
                        verbose_name="Дата окончания рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        help_text="Статус рассылки",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите письмо для рассылки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailings",
                        to="sending_messages.letter",
                        verbose_name="Письмо",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.CreateModel(
            name="AttemptToSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время попытки отправки",
                        verbose_name="Дата попытки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        help_text="Результат попытки отправки",
                        max_length=10,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        blank=True,
                        help_text="Ответ почтового сервера",
                        null=True,
                        verbose_name="Ответ от сервера",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="sending_messages.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
                "ordering": ["-attempt_date"],
            },
        ),
        migrations.CreateModel(
            name="MailingListRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите адрес электронной почты",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        help_text="Введите Ваши фамилию, имя, отчество",
                        max_length=350,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Оставьте свой комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Группы пользователей",
                        related_name="custom_user_groups",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Особые права для пользователя",
                        related_name="custom_user_permissions",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Введите получателей рассылки",
                to="sending_messages.mailinglistrecipient",
                verbose_name="Получатель",
            ),
        ),
    ]
