# Generated by Django 5.2.1 on 2025-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempttosend",
            name="mail_server_response",
            field=models.TextField(
                blank=True,
                default="Нет данных",
                help_text="Ответ почтового сервера",
                null=True,
                verbose_name="Ответ от сервера",
            ),
        ),
        migrations.AlterField(
            model_name="attempttosend",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("failed", "Не успешно")],
                default="failed",
                help_text="Результат попытки отправки",
                max_length=10,
                verbose_name="Статус попытки",
            ),
        ),
    ]
