# Generated by Django 5.2.1 on 2025-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttemptToSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время попытки отправки",
                        verbose_name="Дата попытки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        default="failed",
                        help_text="Результат попытки отправки",
                        max_length=10,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(
                        blank=True,
                        default="Нет данных",
                        help_text="Ответ почтового сервера",
                        null=True,
                        verbose_name="Ответ от сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
                "ordering": ["-attempt_date"],
            },
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=300,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Добавьте содержимое письма",
                        verbose_name="Содержимое письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_sending",
                    models.DateTimeField(
                        help_text="Укажите дату старта рассылки",
                        verbose_name="Дата старта рассылки",
                    ),
                ),
                (
                    "end_sending",
                    models.DateTimeField(
                        help_text="Укажите дату окончания рассылки",
                        verbose_name="Дата окончания рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        help_text="Статус рассылки",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "permissions": [("can_complete_mailing", "Can complete mailing")],
            },
        ),
        migrations.CreateModel(
            name="Recipients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите адрес электронной почты клиента",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        help_text="Введите фамилию, имя, отчество клиента",
                        max_length=350,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Оставьте свой комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
