# Generated by Django 5.2.1 on 2025-07-11 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mailings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца письма",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="letters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="letter",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите письмо для рассылки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailings",
                to="mailings.letter",
                verbose_name="Письмо",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца рассылки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="attempttosend",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddField(
            model_name="recipients",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Группы пользователей",
                related_name="custom_user_groups",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="recipients",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца клиента",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Введите получателей рассылки",
                to="mailings.recipients",
                verbose_name="Получатель",
            ),
        ),
    ]
