# Generated by Django 5.2.1 on 2025-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipients",
            name="groups",
        ),
        migrations.AddField(
            model_name="recipients",
            name="mailing_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Группы пользователей, которые получат рассылку",
                related_name="mailing_recipients",
                related_query_name="mailing_recipient",
                to="auth.group",
                verbose_name="Группы для рассылки",
            ),
        ),
    ]
