# Generated by Django 5.2.1 on 2025-07-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_remove_recipients_groups_recipients_mailing_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attempttosend",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца попытки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempt",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
