# Generated by Django 5.2.1 on 2025-07-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_attempttosend_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempttosend",
            name="emails_sent",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество успешно отправленных сообщений в этой попытке",
                verbose_name="Количество отправленных сообщений",
            ),
        ),
    ]
